import java.util.Scanner;
import java.util.Random;

/**
 * A program which allows the user to
 * play a number guessing game. If the user
 * is wrong, he gets another chance
 */

public class Guess {
    /**
     * The redo method allows the user to try again, if his guess was incorrect
     * @param ans -> the answer generated by the random function. this is constant
     * @param n -> the number passed by the user as the argument
     *          (it is prompted in the check() function)
     */
    public static void redo(int ans, int n) {
        Scanner in = new Scanner(System.in);
        System.out.print("Try again - ");
        n = in.nextInt();
        check(ans, n); // again check if the user was right this time
    }

    /**
     * The check method checks if the user's answer was right or not. Otherwise it calls the
     * redo() method to allow the user to try again. It also prints out too high! or too low!,
     * depending upon the user's input
     * @param ans -> the answer generated by the random function. this is constant
     * @param n -> the number passed by the user as the argument
     *          (it is prompted in the check() function)
     */
    public static void check(int ans, int n) {
        if(ans == n) {
            System.out.println("Your guess was right.");
        } else if(n > ans){
            System.out.print("Too high. ");
            redo(ans, n); // restart the process
        } else {
            System.out.print("Too low. ");
            redo(ans, n); // restart the process
        }
    }
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Random gen = new Random();

        System.out.println("I am thinking of a number between 1 and 100 (including both).");
        System.out.println("Can you guess what it is?\n->");

        // generate a random number from 0 -> 100
        final int number = gen.nextInt(99) + 1;
        int input; // non-constant, used for input
        input = in.nextInt();
        check(number, input);
    }
}